### ISSUE TITLE
Grade prediction model

### ISSUE THREAD

**Issue by KellyHannemann** [dmonllao/moodle-local_testanalytics#1]
I've just found out about this Moodle Analytics API, as a student developer working on a project which wants to help student achieve beter grades and insights through learning analytics.
It would be great if a model for a grade (pass/fail) prediction, based on data such as activity completion in comparison to students who have already passed/failed the course, would be possible

**Comment by dmonllao** [comment]
Hi @KellyHannemann, sorry for the late reply, I missed this email.

That is very possible and it is one of the main aims of Moodle's Analytics API (https://docs.moodle.org/dev/Analytics_API) the API is fully extendable and you can code your own 'target' for pass/fail.

To consider other forms of completion like course completion (https://docs.moodle.org/36/en/Course_completion_settings) or reaching the grade to pass in the course was considered during the development of the students at risk predictive model we included in Moodle 3.4.0 (here you can see an example using course completion as the target: https://github.com/moodlehq/moodle-tool_inspire/blob/master/classes/local/target/course_dropout.php#L159) but we finally opted to focus on students at risk of dropping out (https://docs.moodle.org/36/en/Analytics#Students_at_risk_of_dropping_out)
